version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    platform: linux/amd64  # 아키텍처 명시적 지정
    expose:
      - "8000"
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul  # 시간대 설정
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    platform: linux/amd64
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/config  # SWAG 설정 폴더 전체 매핑
      - /etc/letsencrypt:/etc/letsencrypt  # 인증서 공유
    environment:
      - URL=www.finpilotback.duckdns.org
      - EMAIL=greatsangho@gmail.com
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=
      - TZ=Asia/Seoul
    networks:
      - app-network
    restart: unless-stopped
    cap_add:
      - NET_ADMIN  # 네트워크 기능 확장

networks:
  app-network:
    driver: bridge
    attachable: true

volumes:
  letsencrypt:
    driver: local
