version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    expose:
      - "8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt # 인증서 공유 경로
    depends_on:
      fastapi:
        condition: service_healthy # FastAPI가 준비된 후 시작

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot # 인증 요청 처리 경로 공유
      - /etc/letsencrypt:/etc/letsencrypt # 인증서 저장 경로 공유
    entrypoint: "/bin/sh -c 'while :; do certbot renew --webroot --webroot-path=/var/www/certbot -d finpilotback.duckdns.org -d www.finpilotback.duckdns.org -m greatsangho@gmail.com --agree-tos && sleep 12h; done;'"


networks:
  app-network:
    name: app-network # 명시적 네트워크 이름 사용
    driver: bridge # 명시적 네트워크 드라이버 사용 (선택 사항)
