apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: greatsangho/fastapi-app:latest  # 업로드한 Docker 이미지 이름
          ports:
            - containerPort: 8000
          readinessProbe:                      # Readiness Probe 설정 (선택)
            httpGet:
              path: /health                    # FastAPI의 헬스체크 엔드포인트
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80           # 서비스가 노출하는 포트 (SWAG와 연결)
      targetPort: 8000   # 컨테이너 내부의 FastAPI 포트
  type: ClusterIP         # 내부 네트워크에서만 접근 가능 (SWAG가 프록시 역할)
